### ISSUE TITLE
something wrong going on while running the install script ....

### ISSUE THREAD

**Issue by nmsoares** [whiskerz007/proxmox_hassos_install#1]
Hi all. Congrats on the great work!
I've tried to install this on proxmox and got this error:

root@proxmox:~# TMP=`mktemp -d`;pushd $TMP > /dev/null;wget -qO - https://raw.githubusercontent.com/whiskerz007/proxmox_hassos_install/master/install.sh | bash;popd > /dev/null;rm -rf $TMP;unset TMP 
Traceback (most recent call last):
  File "<stdin>", line 4, in <module>
KeyError: 'ids'
root@proxmox:~# 

What am I doing wrong ? Please advise.
Thanks in advance.

**Comment by willngton** [comment]
> Hi all. Congrats on the great work!
> I've tried to install this on proxmox and got this error:
> 
> root@proxmox:# TMP=`mktemp -d`;pushd $TMP > /dev/null;wget -qO - https://raw.githubusercontent.com/whiskerz007/proxmox_hassos_install/master/install.sh | bash;popd > /dev/null;rm -rf $TMP;unset TMP
> Traceback (most recent call last):
> File "", line 4, in 
> KeyError: 'ids'
> root@proxmox:#
> 
> What am I doing wrong ? Please advise.
> Thanks in advance.

Script is not considering that you have 0 VM created, until fix, the quickest workaround would be you create a VM (any type, even does not need to initiate it) , and run the scrip again.

Regards.
