### ISSUE TITLE
Can't select storage pool?

### ISSUE THREAD

**Issue by iroQuai** [whiskerz007/proxmox_hassos_install#103]
When the script starts, i get asked which storage pool i'd like to install on (i've got 2 cifs and the local-lvm i'd like to install on). I have no idea which button to press to select a storage. 

I've tried almost every button i could think of. Enter just resets the screen. Only arrows up & down seem to work. Tab works to go to the ok and cancel buttons. Left-right arrows work there. Escape works to cancel the script. 

I have no idea how to proceed in this script! Anyone has a tip for me? :)

edit: tried as root via both the proxmox gui shell as via putty...

**Comment by iroQuai** [comment]
For some reason i didn't try the spacebar..... sorry! issue closed...

**Comment by KyleJFischer** [comment]
@iroQuai Just wanted to say, you making this issue helped me out, as I was only pressing the Enter key and confused why it wasn't working. Wouldn't have tried space without your follow up so thank you!
