### ISSUE TITLE
DHCP / Static commands gives me an error

### ISSUE THREAD

**Issue by fribse** [whiskerz007/proxmox_hassos_install#112]
Hi @whiskerz007 
I installed the HA with your script ages ago, and it is a thing of beauty! I've also guided other people to the script, as it's simply too easy to use.
Back in the days, I changed the HA to use a static IP, but I've since found out that my unifi router doesn't update it's internal DNS server with the ip address if it's set static, so I would like for it to be dhcp given (and then do a dhcp reservation).
My config looks like this in nmcli:
![image](https://user-images.githubusercontent.com/13660621/120884850-e976ed00-c5e5-11eb-8e7f-a5aa937e5da8.png)
This is all well and fine for static, so I typed your command to quickly convert it to dhcp, and I got this message:
![image](https://user-images.githubusercontent.com/13660621/120884866-0ad7d900-c5e6-11eb-8021-c3d7d9a1d713.png)

I'm sure it's because things were done differently back then, but can you help me out in figuring out how to fix this?

**Comment by trSSFreAkY** [comment]
It seems you can change this in the ui of homeassistant nowadays. Also had this problem but figured it out.
Go to Supervisor - System and under Host you have a change "button" besides the ip address. I changed it to what i wanted there and it seems to work :)

**Comment by fribse** [comment]
@trSSFreAkY Ahh, you are absolutely right, thanks!
