### ISSUE TITLE
Hassio Samba Addon

### ISSUE THREAD

**Issue by SirRedZ** [whiskerz007/proxmox_hassos_install#12]
I love what you've done to make this easy for us. Thank you.

I am trying to add Samba Addon- It can't find the eth0 interface, or any of the other variants I tried (net0, net1). What is the correct setting and method to use Samba addon?

Secondly, how can I rename the host as my production samba shares "Hassio" and I would like the dev to share " Hasiso-dev" or similar.

Thank you !

**Comment by whiskerz007** [comment]
@SirRedZ I have made changes to the repo which should solve your problem. If there is nothing further, I will close this issue after 48 hours.
