### ISSUE TITLE
CPU is constant high using discovery on proxmox and hassos

### ISSUE THREAD

**Issue by helto4real** [whiskerz007/proxmox_hassos_install#16]
After using the script and changing the ip to static ip as instructed, hassio started fine (awesome job). But CPU is running high (constant 80-90) even now after one hour. I am running this on a 32 Gig memory, I3 256G ssd. My hassio install on a debian vm runs at 1-3% cpu. Efter testing some stuff i removed the discovery component and the CPU issue was gone! Anyone seeing this?

**Comment by SirRedZ** [comment]
I have a Celeron J3455 with 2 Gigs (allocated), 240 gig HDD ( 32gig allocated) and I have a secnd implementation (identical) -- Im showing 5-10% CPU usage for each VM, it does peak to 50 or 60 at times for a second or two (I have 3 cameras running- so I think that is the explanation).

Not sure why you are seeing this. This script sure made it easy for me to get this up and running, completely new to Linux.

Good luck!

**Comment by helto4real** [comment]
I found out what it was. It was the yeelight discovery that was causing the problems. If I disabled the yeelight discovery it worked. @SirRedZ ..

**Comment by whiskerz007** [comment]
Issue seems to be resolved.
