### ISSUE TITLE
Multiple instances

### ISSUE THREAD

**Issue by jnpetersen** [whiskerz007/proxmox_hassos_install#20]
Do you know how to make it so you can deploy this as many times as needed to one proxmox environment?  I want to be able to have a development environment that I work with, so that I'm not messing around with the one running the house, but be able to commit my code and then pull from production for any code I want brought over.

**Comment by rottison** [comment]
I just used the same CLI line to install hassio and hassioDEV gave each one a there own static ip and was of to the races and seems to work fine

**Comment by whiskerz007** [comment]
@jnpetersen If you want to use multiple instances at the same time, you should change the name in the VM OS. This can be accomplished by following [these](https://github.com/whiskerz007/proxmox_hassos_install#change-hostname) instructions.
