### ISSUE TITLE
Does not work on VE 5.4-3

### ISSUE THREAD

**Issue by dutchmhk** [whiskerz007/proxmox_hassos_install#21]
When running the command in Proxmox Shell or in a SSH session
Nothing happens at all, no errors no nothing
Running a fresh Proxmox 5.4-3 install on a BareMetal Dell machine 

wget -qO - https://raw.githubusercontent.com/whiskerz007/proxmox_hassos_install/master/install.sh | bash -s local-lvm

**Comment by jdenver13** [comment]
I think you'll find its a zero after the 'q' and not a capital 'O' as in wget -q0 -................

**Comment by dutchmhk** [comment]
According to the help file, it needs to be an "O" (Download to output file)

I tried with an "0" but no luck - see below log

Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
permitted by applicable law.
root@vm:~# wget -q0 -
https://raw.githubusercontent.com/whiskerz007/proxmox_hassos_install/master/install.sh
| bash -s local-lvm
wget: invalid option -- '0'
Usage: wget [OPTION]... [URL]...

Try `wget --help' for more options.
root@vm:~# wget --help
GNU Wget 1.18, a non-interactive network retriever.
Usage: wget [OPTION]... [URL]...

Mandatory arguments to long options are mandatory for short options too.

Startup:
  -V,  --version                   display the version of Wget and exit
  -h,  --help                      print this help
  -b,  --background                go to background after startup
  -e,  --execute=COMMAND           execute a `.wgetrc'-style command

Logging and input file:
  -o,  --output-file=FILE          log messages to FILE
  -a,  --append-output=FILE        append messages to FILE
  -d,  --debug                     print lots of debugging information
  -q,  --quiet                     quiet (no output)
  -v,  --verbose                   be verbose (this is the default)
  -nv, --no-verbose                turn off verboseness, without being quiet
       --report-speed=TYPE         output bandwidth as TYPE.  TYPE can be
bits
  -i,  --input-file=FILE           download URLs found in local or external
FILE
  -F,  --force-html                treat input file as HTML
  -B,  --base=URL                  resolves HTML input-file links (-i -F)
                                     relative to URL
       --config=FILE               specify config file to use
       --no-config                 do not read any config file
       --rejected-log=FILE         log reasons for URL rejection to FILE

Download:
  -t,  --tries=NUMBER              set number of retries to NUMBER (0
unlimits)
       --retry-connrefused         retry even if connection is refused
  -O,  --output-document=FILE      write documents to FILE
  -nc, --no-clobber                skip downloads that would download to
                                     existing files (overwriting them)
  -c,  --continue                  resume getting a partially-downloaded
file

Den tor. 18. apr. 2019 kl. 22.15 skrev denver <notifications@github.com>:

**Comment by AalianKhan** [comment]
Is it working now?  I had a similar problem and found out that I couldn't ping 8.8.8.8 thus I couldn't connect to the internet. If that's the case then there is definitely something wrong with your network adapter. My problem was I didn't enable autostart.

**Comment by whiskerz007** [comment]
Issue seems to be resolved.
