### ISSUE TITLE
Script does nothing

### ISSUE THREAD

**Issue by jmheist** [whiskerz007/proxmox_hassos_install#29]
latest proxmox server, copy/pasted script and thing happens, immediatly finishes and left at prompt.

**Comment by AalianKhan** [comment]
same with me

**Comment by jmheist** [comment]
if I try just:
wget https://raw.githubusercontent.com/whiskerz007/proxmox_hassos_install/master/install.sh
I get:
unable to resolve host address ‘raw.githubusercontent.com’

**Comment by AalianKhan** [comment]
I got mine working. My proxmox wasn't able to connect to the internet

**Comment by AalianKhan** [comment]
Try going on the terminal and write ping 8.8.8.8 

I it is working then I'm not sure. If it's not then it's most probably your network adapter. My problem was I didn't have autostart enabled on my adapter. If you don't understand or need further help then just contact me and I will send you detailed instructions and images

**Comment by jmheist** [comment]
Ok, I'l give that a shot this evening. thanks!

**Comment by jmheist** [comment]
ping works just fine. :(

**Comment by AalianKhan** [comment]
Try ping google.com

**Comment by jmheist** [comment]
root@pve:~# ping google
ping: google: Temporary failure in name resolution

**Comment by jmheist** [comment]
root@pve:~# ping google.com
ping: google.com: Temporary failure in name resolution

**Comment by AalianKhan** [comment]
You are supposed to get 
root@proxmox:~# ping google.com
PING google.com (172.217.164.238) 56(84) bytes of data.
64 bytes from yyz12s05-in-f14.1e100.net (172.217.164.238): icmp_seq=1 ttl=55 time=15.1 ms
64 bytes from yyz12s05-in-f14.1e100.net (172.217.164.238): icmp_seq=2 ttl=55 time=21.2 ms
...

**Comment by AalianKhan** [comment]
did you try reinstalling proxmox

**Comment by jmheist** [comment]
/etc/resolv.conf had:

search localdomain.local
nameserver 192.168.1.7

which might have been misconfigued when I ran pihole

**Comment by jmheist** [comment]
changed the entry to 8.8.8.8 and we are up and running again. yikes, that was a pain.

**Comment by AalianKhan** [comment]
Nice

**Comment by nickdaria** [comment]
> changed the entry to 8.8.8.8 and we are up and running again. yikes, that was a pain.

Just an update here. The problem is that the default DNS uses localhost. You can use any of the following.

1.1.1.1: Cloudflare
8.8.8.8/8.8.4.4: Google

**Comment by whiskerz007** [comment]
Issue seems to have been resolved.
