### ISSUE TITLE
resize disk

### ISSUE THREAD

**Issue by fragolinux** [whiskerz007/proxmox_hassos_install#3]
hi, just run your script, changed ram to 2gb and hd resized via proxmox web gui to 16gb (from original 6gb)... how to enlarge internal filesystem, now? i see /dev/sda8 of 5.3gb... thanks

**Comment by whiskerz007** [comment]
The first time the VM boots, it will expand `/dev/sda8` to the end of the drive. Subsequent boots will not perform that operation. I will look into a process to expand the disk after the first boot.

**Comment by fragolinux** [comment]
hi and thanks :)
on other distros, like raspbian or armbian, this is done by some script which is triggered on 1st boot, then auto destroys itself... or, better, on those OS usually it's run as a parameter on command line to the init process on 1st boot, maybe we can take that and rerun...

something like this: https://github.com/urho3d/rpi-sysroot/blob/master/usr/lib/raspi-config/init_resize.sh

**Comment by whiskerz007** [comment]
@fragolinux I have made changes to the repo which should solve your problem. If there is nothing further, I will close this issue after 48 hours.
