### ISSUE TITLE
Guest has not initialized the display (yet)

### ISSUE THREAD

**Issue by oldfart101** [whiskerz007/proxmox_hassos_install#32]
I get this message
Left it for an hour!!!

Worked about 3 weeks ago, not working now

**Comment by raystream** [comment]
same here.
when using the UEFI Bios the vm does not start but uses 90-100% cpu.

**Comment by tel196** [comment]
I am getting the same, it just sits and will not start up, I have tried changing the drive to IDE etc and bios  but nothing will make it boot

**Comment by gigios** [comment]
Unfortunately I have the same problem.

**Comment by gigios** [comment]
Sorry for the double post!
I have found today an update in the Proxmox! After the installation of these updates, I have retried the execution of the script and NOW works!

**Comment by oldfart101** [comment]
Yes - update, then script works
