### ISSUE TITLE
Not working on Proxmox 6

### ISSUE THREAD

**Issue by arlling** [whiskerz007/proxmox_hassos_install#34]
There seems to be an issue using this script on Proxmox 6.0
Fails to boot UEFI

**Comment by Norec39** [comment]
No problem for me on proxmox v6.0-4

**Comment by zenmisael** [comment]
fail to boot UEFI  on proxmox Virtual Environment 6.0-11.
stop/loop on EUFI boot shell

**Comment by shuttle842** [comment]
same with me

**Comment by Niko9911** [comment]
![image](https://user-images.githubusercontent.com/4658966/69217488-79298780-0b77-11ea-89fc-e28ba28e0ede.png)

```
proxmox-ve: 6.0-2 (running kernel: 5.0.21-5-pve)
pve-manager: 6.0-11 (running version: 6.0-11/2140ef37)
pve-kernel-helper: 6.0-12
pve-kernel-5.0: 6.0-11
pve-kernel-5.0.21-5-pve: 5.0.21-10
pve-kernel-5.0.15-1-pve: 5.0.15-1
ceph-fuse: 12.2.11+dfsg1-2.1+b1
corosync: 3.0.2-pve4
criu: 3.11-3
glusterfs-client: 5.5-3
ksm-control-daemon: 1.3-1
libjs-extjs: 6.0.1-10
libknet1: 1.13-pve1
libpve-access-control: 6.0-3
libpve-apiclient-perl: 3.0-2
libpve-common-perl: 6.0-7
libpve-guest-common-perl: 3.0-2
libpve-http-server-perl: 3.0-3
libpve-storage-perl: 6.0-9
libqb0: 1.0.5-1
lvm2: 2.03.02-pve3
lxc-pve: 3.2.1-1
lxcfs: 3.0.3-pve60
novnc-pve: 1.1.0-1
proxmox-mini-journalreader: 1.1-1
proxmox-widget-toolkit: 2.0-8
pve-cluster: 6.0-7
pve-container: 3.0-10
pve-docs: 6.0-8
pve-edk2-firmware: 2.20190614-1
pve-firewall: 4.0-7
pve-firmware: 3.0-4
pve-ha-manager: 3.0-3
pve-i18n: 2.0-3
pve-qemu-kvm: 4.0.1-5
pve-xtermjs: 3.13.2-1
qemu-server: 6.0-13
smartmontools: 7.0-pve2
spiceterm: 3.1-1
vncterm: 1.6-1
zfsutils-linux: 0.8.2-pve2
```

**Comment by Norec39** [comment]
Finally I have multiple problems with this script then I’ve install hassio on docker on à Debian VM

**Comment by Niko9911** [comment]
@Norec39 I encountered 502 gateway errors when using docker setup. 

Install addon.
Add in to menu.
Click addon.
White page opens with 502.


Do you have this issue?

**Comment by Norec39** [comment]
@Niko9911 for which addon ? (I can test on my own installation)

**Comment by Niko9911** [comment]
@Norec39 Basically any. I tried myself addons from community section, many of them. 

Node-Red, Logs, Shell, Spotify, etc. As far I tested, it affected all addons and I wasn't even able to get any logs about this error by using `docker logs -f` on all containers and trying to cause the error.

Thank you for your effort in advance!

**Comment by leschNUX** [comment]
same issue on proxmox Virtual Environment 6.0-12

**Comment by Norec39** [comment]
@Niko9911 on docker I try to install Grafana addon and no problem for me you have to wait a few seconds before clicking on the web UI and no 502 error, for the first time I click trough the addon category and choose the web UI button, not the button in the right sidebar ;)

**Comment by Niko9911** [comment]
@Norec39 There was no change, it's somehow faulty on my end. Anyways, e45b4e2 fixed my problems getting stuck in the uefi.
