### ISSUE TITLE
Hassio update problem

### ISSUE THREAD

**Issue by unf0rg0tt3n** [whiskerz007/proxmox_hassos_install#35]
Since update 100.3 it won't update any further (to 102.2).

`19-11-28 21:12:45 WARNING (MainThread) [hassio.homeassistant] Don't wait anymore of Home Assistant startup!
19-11-28 21:12:45 CRITICAL (MainThread) [hassio.homeassistant] HomeAssistant update fails -> rollback!
19-11-28 21:12:45 INFO (MainThread) [hassio.homeassistant] Update Home Assistant to version 0.100.3
19-11-28 21:12:45 INFO (SyncWorker_16) [hassio.docker.interface] Update image homeassistant/qemux86-64-homeassistant:0.102.2 to homeassistant/qemux86-64-homeassistant:0.100.3
19-11-28 21:12:45 INFO (SyncWorker_16) [hassio.docker.interface] Pull image homeassistant/qemux86-64-homeassistant tag 0.100.3.
19-11-28 21:12:47 INFO (SyncWorker_16) [hassio.docker.interface] Stop homeassistant application
19-11-28 21:12:52 INFO (SyncWorker_16) [hassio.docker.interface] Clean homeassistant application
19-11-28 21:12:52 INFO (SyncWorker_17) [hassio.docker.homeassistant] Start homeassistant homeassistant/qemux86-64-homeassistant with version 0.100.3
19-11-28 21:13:02 INFO (MainThread) [hassio.homeassistant] Detect a running Home Assistant instance
19-11-28 21:13:02 INFO (MainThread) [hassio.homeassistant] Successful run Home Assistant 0.100.3
19-11-28 21:13:02 INFO (SyncWorker_8) [hassio.docker.interface] Cleanup images: ['homeassistant/qemux86-64-homeassistant:0.102.2']`

Not sure if problem with qemu image or hassio itself.

**Comment by darekhome** [comment]
I thin k I have the same problem...
Any solution appeared in this area?
I tried few times the update - no success...

<img width="256" alt="Home Assistant" src="https://user-images.githubusercontent.com/55238173/70868690-71e17800-1f83-11ea-983a-2498faa147e2.png">

**Comment by unf0rg0tt3n** [comment]
> I think I have the same problem...
> Any solution appeared in this area?
> I tried few times the update - no success...
> 
> <img alt="Home Assistant" width="256" src="https://user-images.githubusercontent.com/55238173/70868690-71e17800-1f83-11ea-983a-2498faa147e2.png">

Yea, issue resolved. Removed the old school api password and it updated
