### ISSUE TITLE
USB port can not be mapped from 'proxmox' to 'hass.io'...

### ISSUE THREAD

**Issue by darekhome** [whiskerz007/proxmox_hassos_install#38]
On proxmox I have set-up 'USB' device... And it has 'usb0'.

<img width="238" alt="usb" src="https://user-images.githubusercontent.com/55238173/71447870-8f0d0800-2734-11ea-8b09-577cebe64906.png">

However in 'hass.io' I do not see this port (ls -l /dev | more):

<img width="308" alt="usb ports" src="https://user-images.githubusercontent.com/55238173/71447878-a815b900-2734-11ea-8a6a-5ca2239c9871.png">

However under 'hassi.io' menu; 'hardware' I see only ports like 'ttySx':
<img width="274" alt="tty" src="https://user-images.githubusercontent.com/55238173/71447892-de533880-2734-11ea-95ad-d0d74839169f.png">

Any additional settings are needed to see the USB device in 'hass.io' ???

**Comment by darekhome** [comment]
Having some time - I've installed the same configuration on other PC (Dell Optiplex 780).
I mean Proxmox + this install script.
The issue is the same - USB port can not be pass-through. It is defined in Proxmox,
but it is not visible in hass.io.

Looks like some bug in HassOS???


<img width="583" alt="hassio2" src="https://user-images.githubusercontent.com/55238173/71563620-0d4e0f00-2a93-11ea-9b11-607772d79841.png">


<img width="363" alt="hassio2_1" src="https://user-images.githubusercontent.com/55238173/71563631-2d7dce00-2a93-11ea-834c-7724edc1b1d2.png">

**Comment by whiskerz007** [comment]
Maybe you are experiencing a limitation of drivers that are not present in the VM. What device are you trying to passthrough to the VM?

**Comment by darekhome** [comment]
Yes, you are right...
This going to be solved with HassOS 4.0 - "Add support for TI USB 3410 or 5052 serial devices"...

[https://github.com/home-assistant/hassos/pull/542](url)

**Comment by qbss** [comment]
Any news on this?  I'm having the same issue with my system and suppose I'll have to skip using zwave devices unless this gets resolved or I possibly move to another pc that doesn't have driver limitations.

**Comment by qbss** [comment]
I'm running HassOS 4.10 but I suppose that maybe its a driver issue with the older (around the 2008-10 time period) Shuttle brand PC that I'm running Proxmox on.
