### ISSUE TITLE
hassos installer hangs

### ISSUE THREAD

**Issue by jamesgreeley** [whiskerz007/proxmox_hassos_install#40]
The script doesnt appear to be working on 6.1-3

Not sure if its script or hassos related.

![image](https://user-images.githubusercontent.com/3008387/71683445-7b901b80-2d8a-11ea-9dab-92db5fe576f3.png)

**Comment by jamesgreeley** [comment]
appears to be related to this: https://github.com/home-assistant/hassio-supervisor/issues/859

**Comment by jamesgreeley** [comment]
It appears home assistant has booted. Please ignore.

**Comment by timmillwood** [comment]
I have the same issue

**Comment by timmillwood** [comment]
![image](https://user-images.githubusercontent.com/151519/71780616-b11c4b00-2fbc-11ea-9254-8193b51a69d1.jpg)

**Comment by mkanet** [comment]
I'm having the same exact issue.  However, this thread is closed without a solution/fix.   Did anyone figure out what's wrong?

**Comment by VarenDerpsAround** [comment]
Try pressing the enter key a couple of times if you are at that exact same screen

**Comment by VarenDerpsAround** [comment]
Also, consider double checking your DNS settings on the host.
