### ISSUE TITLE
Guest has not initialized the display yet

### ISSUE THREAD

**Issue by mattjbailey** [whiskerz007/proxmox_hassos_install#43]
After running the script and the VM gets created, when I turn on the VM the console never shows anything except: Guest has not initialized the display yet. The CPU runs at 100 percent (I've given it over 40 minuets) Running Proxmox Virtual Environment 6.0-11

**Comment by mattjbailey** [comment]
Update: I only get this when changing the install drive.

**Comment by mattialatino** [comment]
Seconding this.
I'm experiencing this issue whether or not I resize the drive.
Running Proxmox 6.1-7.

**Comment by whiskerz007** [comment]
How much RAM did you assign to the VM? I have experienced Proxmox not properly starting a VM when I allocate too much RAM with PCI device passthrough. If you run the script to install the VM and only start the container (without modifying any hardware settings) do you still experience this issue?

**Comment by mattialatino** [comment]
> 
> 
> How much RAM did you assign to the VM? I have experienced Proxmox not properly starting a VM when I allocate too much RAM with PCI device passthrough. If you run the script to install the VM and only start the container (without modifying any hardware settings) do you still experience this issue?

So, this did it! I was initially assigning the VM 4GB RAM before the first boot up. Tried booting it up without applying any hardware changes and it worked as expected. Thank you!
