### ISSUE TITLE
Can I use dual network segments?

### ISSUE THREAD

**Issue by fliesyan** [whiskerz007/proxmox_hassos_install#50]
The device wo n’t work as long as I have dual network cards installed
Is there a new way?

**Comment by whiskerz007** [comment]
I do not understand what you mean by `the device won't work`. Do you mean the VM will not start? Do you mean you are not able to access the web interface of Home Assistant? I tried to create a new VM and add a second NIC and noticed that the second NIC got an IP address but not the first NIC. Does this explain the issue you are having?

**Comment by fliesyan** [comment]
> 我不明白你的意思`the device won't work`。您是說VM無法啟動嗎？您是否表示無法訪問Home Assistant的Web界面？我嘗試創建一個新的VM並添加第二個NIC，並註意到第二個NIC獲得了IP地址，但沒有第一個NIC。這是否可以解釋您遇到的問題？

Single network card can be used normally
Two network cards, the system cannot be used

**Comment by whiskerz007** [comment]
I believe you are experiencing a limitation that is within the Home Assistant developers domain. Proxmox seems to be preforming as expected when you add another NIC to the VM. I would raise this issue with the Home Assistant team.

**Comment by fliesyan** [comment]
thank
