### ISSUE TITLE
Boot Fail Issue

### ISSUE THREAD

**Issue by eracknaphobia** [whiskerz007/proxmox_hassos_install#59]
I've had to re-install home assistant multiple times because I get this error seemingly at random when I reboot my vm. Sometimes the reboot works but most times it doesn't. I've gotten better at avoiding this by just using the ha command line and restarting by using `core restart`. Any pointers at what my issue may be? 

![image](https://user-images.githubusercontent.com/8268725/80528025-43c56900-8963-11ea-97a5-f9b6bc46a7c5.png)

![image](https://user-images.githubusercontent.com/8268725/80528433-ebdb3200-8963-11ea-813d-c92972026b84.png)

**Comment by robgardien** [comment]
I've experienced the same issue, had to restore a backup and when I stop the machine and start it again the error appears

**Comment by eracknaphobia** [comment]
Seems to happen when I do a HA version update from the web frontend. I'll wait 10 min or so and check the logs which make it look like the system is running, there's just no frontend. This is where I use to manually reboot the vm the and pretty much kill it.

To get around this i go to the console on proxmox and issue a `core stop` (multiple times if necessary), rename my config so the system can start fresh, then i do a `core start` and usually it'll start back up. Then I place my configuration.yaml file back in the config folder and start it back up and that usually works.

@robgardien Do you use tensorflow by chance? I have a feeling it might be this that is causing some [issues](https://community.home-assistant.io/t/tensorflow-causing-restart-loop/109627/25?u=eracknaphobia) for me initially.

**Comment by robgardien** [comment]
@eracknaphobia No I don't use tensorflow, it happens after an upgrade of home assistant. The systems resources are very high and it looks like the system is running, there's just no frontend as you described. A reboot seems to work, a stop and start seems to cause the error

**Comment by eracknaphobia** [comment]
Ok thanks, maybe tensorflow has nothing to do with it. 

I just updated from 109.4 to 109.5 strictly from console commands.

- core stop
- core update
- core start - no frontend after 10 minutes, log file grows with no apparent errors just normal log traffic
- core restart - system comes up fully 🤷‍♂️

**Comment by eracknaphobia** [comment]
I'm currently in limbo mode after trying to update to 109.6. can't stop / start core I noticed ram is maxed out. memory leak issue?

![image](https://user-images.githubusercontent.com/8268725/81477540-3cfde800-91e6-11ea-9aa0-7a8a7530e36a.png)

![image](https://user-images.githubusercontent.com/8268725/81477547-4a1ad700-91e6-11ea-8ce5-cacdce3f963b.png)

**Comment by robgardien** [comment]
I've updated proxmox using **apt-get dist-upgrade** from the pve shell and I haven't had the problem since, maybe it's worth trying?

**Comment by eracknaphobia** [comment]
Thanks, I'll give it a shot.

**Comment by eracknaphobia** [comment]
Updating proxmox didn't solve my issue. I'm currently stuck in limbo trying to update Home assistant to 0.110.1

**Comment by eracknaphobia** [comment]
Still having issues. Usually when I try to do anything with restarting / updating when my memory usage is 90% or more.

**Comment by robgardien** [comment]
I'm also still having issues. Works fine while running but the error occurs when restarting. I have to restore a backup when this problem occurs

**Comment by woody4165** [comment]
I'm having same issue, but it occurs randomly, meaning that for some dasys all is working well, then suddenly if I do a shutdown or reboot of the VM I get this error.
I noticed that it has started after upgrading Proxmox to 6.2.x

If I restore a snapshot, the error is still there, only if I restore a backup of the entire VM the error does not show anymore, until next one.

It seems to be related to the UEFI disk.

I tried to follow this guide, but after "elect 'Add Boot Option':" I don't have nothing to select and I'm stuck

**Comment by eracknaphobia** [comment]
@woody4165  Thanks for the info about the backups. I was using snapshots and noticed they wouldn't boot either. I will look into making Stop backups instead for now. Should save me time as I've been re-creating the vm from scratch and importing my homeassistant snapshot when things go south.

**Comment by eracknaphobia** [comment]
Anyone know if it is normal to have the `link becomes ready` message pop up so many times? I'm currently trying to update to 0.110.6 and the frontend is down but the console is running. 
![image](https://user-images.githubusercontent.com/8268725/84164308-6194ec00-aa40-11ea-8350-fefc91da6502.png)

BTW, proxmox is running on a nuc i7 (5th gen) with an nvme ssd, so i would think boots would be much faster than what they are currently.

**Comment by swm5126** [comment]
Yeah I'm having this same issue since Proxmox updated itself. 

I re ran the script and it works until I restart the VM, then it wont boot. Seems like there is some kind of UEFI issue. Haven't been able to get the boot menu to work correctly either like mentioned on the Proxmox forums.

**Comment by FordMustang0288** [comment]
I too am having this issue. Glad I'm not going crazy.
![image](https://user-images.githubusercontent.com/31976175/92907653-814b0000-f3f3-11ea-9cf8-3412d3217a1b.png)

**Comment by swm5126** [comment]
I ended up following this guide: [](https://community.home-assistant.io/t/supervised-install-on-proxmox/194460).

After I got it up and running I just loaded my latest full snapshot backup from HA and I was up and running again.

**Comment by eracknaphobia** [comment]
I have not had this error reappear in a long time. So whatever was the cause must have been patched some where along the way.
