### ISSUE TITLE
Static IP address

### ISSUE THREAD

**Issue by 01kbpatel** [whiskerz007/proxmox_hassos_install#6]
How do you assign static ip address to the VM.

I copied VM MAC address to my DHCP server, assigning ip address to MAC address, then restarted the VM but VM's ip address is not what is assigned by DHCP

**Comment by whiskerz007** [comment]
There might be an active DHCP lease for that MAC address still in the router. Try shutting down the VM and then reboot the router after changing DHCP reservations. This should clear all DHCP leases on the router. Start the VM after the router is back to normal operation.

**Comment by whiskerz007** [comment]
@01kbpatel I have made changes to the repo which should solve your problem. If there is nothing further, I will close this issue after 48 hours.
