### ISSUE TITLE
Unable to select storage pool for installation

### ISSUE THREAD

**Issue by a5pire** [whiskerz007/proxmox_hassos_install#65]
Run the command `bash -c "$(wget -qLO - https://github.com/whiskerz007/proxmox_hassos_install/raw/master/install.sh)"` then presented with an option to choose storage pool for the installation. No option is able to be selected. Result is the same via proxmox shell in the browser and ssh from linux terminal.

Intel Nuc 8i7hvk
Proxmox 6.0-4
Linux Kernel 5.0.15-1

**Comment by kennethrorydunn** [comment]
Are you using spacebar to make the selection and then tabbing to OK?

**Comment by a5pire** [comment]
This must have been the only method i didnt try... All working now.. Thanks.
