### ISSUE TITLE
[SOLVED] [ERROR] 0@96 Github has returned an error. A rate limit may have been applied to your connection.

### ISSUE THREAD

**Issue by woody4165** [whiskerz007/proxmox_hassos_install#67]
Hi @whiskerz007 

I've used your script several times and for this I thank you very much.

Today I'm getting this error.

```
Getting URL for latest Home Assistant disk image...
[ERROR] 0@96 Github has returned an error. A rate limit may have been applied to your connection.
```

What can I check?

Thanks

**PS: the error was due to the fact that a new version of HassOs was coming and the vdmk file was not yet available.**

**Comment by dangerbock** [comment]
hi...
i also get the same error

**Comment by alexeyzel** [comment]
Hello! I have the same error too.

```
root@proxmox:~# bash -c "$(wget -qLO - https://github.com/whiskerz007/proxmox_hassos_install/raw/master/install.sh)"
[INFO] Using 'local-lvm' for storage location.
[INFO] Container ID is 100.
Getting URL for latest Home Assistant disk image...
[ERROR] 0@96 Github has returned an error. A rate limit may have been applied to your connection.

```

**Comment by dangerbock** [comment]
The problem is that @whiskerz007 expect an "vmdk.gz" extencion from the JSON file but that release don't exist anymore on this JSON "https://api.github.com/repos/home-assistant/hassos/releases/latest"

**Comment by woody4165** [comment]
> it just have been released HassOS Release-4 build 7 (Stable) 5 hours ago so maybe they still compilling everything the last stable with withe de VMWARE image was the build 6
> https://github.com/home-assistant/operating-system/releases

Probably this is the reason, thanks.
I've downloaded locally the `install.h` but I don't find a way to download this version https://github.com/home-assistant/operating-system/releases/download/3.13/hassos_ova-3.13.vmdk.gz

**Comment by dangerbock** [comment]
at the moment i'm not abble to test on promox but for now you can do an workarround
edit install.sh and insert this line:

```
EOF
)
**URL="https://github.com/home-assistant/operating-system/releases/download/4.6/hassos_ova-4.6.vmdk.gz"**
if [ -z "$URL" ]; then
  die "Github has returned an error. A rate limit may have been applied to your connection."
fi
```

**Comment by alexeyzel** [comment]
Did not worked. after addint this new line i have new error:

```
[INFO] Using 'local-lvm' for storage location.
[INFO] Container ID is 100.
Getting URL for latest Home Assistant disk image...
bash: line 95: url: command not found
[ERROR] 127@95 Unknown failure occured.
```

**Comment by alexeyzel** [comment]
I changed line 87 from

`url = 'https://api.github.com/repos/home-assistant/hassos/releases/latest'`

to

`url = 'https://api.github.com/repos/home-assistant/operating-system/releases/26003913'`

And it worked.
New name of repo is "operating-system" and 26003913 is release ID of previous version with "vmdk.gz" extension.

**Comment by austwhite** [comment]
You could also try https://api.github.com/repos/home-assistant/operating-system/releases/latest so it is more universal rather than just one release

**Comment by austwhite** [comment]
I just noticed release 26003913 has a Beta version (RC) of HASSOS with it, 4.6, that potentially has a bugs.   You can't downgrade back to 3.13 and 4.7 is not available as update yet.

**Comment by dangerbock** [comment]
Yes 4.6 is a pre release

**Comment by dangerbock** [comment]
@austwhite version 4 build 7  ow have de vmdk so the original script should work

https://github.com/home-assistant/operating-system/releases/tag/4.7

**Comment by woody4165** [comment]
Thanks all for the suggestion and understanding the problem.

I think now I can close this issue since was not a real issue, but just something related to a new HassOs version coming and the VDMK file was still not available.

**Comment by whiskerz007** [comment]
The repo reference has been updated in the script.

**Comment by dangerbock** [comment]
@woody4165 thank you for the great work

**Comment by pedroponte** [comment]
> The repo reference has been updated in the script.

could it be added to the patch slow script also please? TIA

https://github.com/whiskerz007/proxmox_hassos_install/raw/patch-slow-zfs/install.sh
