### ISSUE TITLE
hassio: port  entered forwarding state

### ISSUE THREAD

**Issue by szurr** [whiskerz007/proxmox_hassos_install#68]
Hi
I don't know is this a issue with vm but i try copule of options with static ips etc. 
My vm sometimes don't get back after update and right now only errors i found was this in vm consol
hassio: port 4(vethe217dc6) entered forwarding state.... then after many many port tested it eventulay found working one (but i guess that mayby my bootloop is from this)
thanks and cheers

**Comment by whiskerz007** [comment]
This message is normal and represents an interface that is used by Docker in the VM. If you are having a problem with updating the OS and the HA interface not returning, make sure you have enough disk space in the VM to accept the new ones. I would suggest you have a couple of GB free for updates.

**Comment by szurr** [comment]
Ok thank you very much. I shoud have enough space but i'll check.
Thanks for your work cheers
