### ISSUE TITLE
[ERROR] 4@127 Unknown failure occured.

### ISSUE THREAD

**Issue by titof2375** [whiskerz007/proxmox_hassos_install#69]
hello, I followed your script to install ha on a vm on proxmox and I find myself with an error ([ERROR] 4 @ 127 Unknown failure occured.) when creating the VM, I tried to redo the handle many times and always the same problem.

**Comment by whiskerz007** [comment]
New commit has been pushed. Please confirm that the script now works.

**Comment by titof2375** [comment]
always the same error

**Comment by whiskerz007** [comment]
Please respond with the output of `pvesm status | awk '{printf "%-14s\t%s\n", $1, $2}'` and the name of the storage pool you are choosing.

**Comment by titof2375** [comment]
![bbbbb](https://user-images.githubusercontent.com/31250165/83174061-19a9c700-a11a-11ea-8f6e-961179cbb786.PNG)

**Comment by whiskerz007** [comment]
Which storage pool are you trying to setup the VM on?
