### ISSUE TITLE
running script error no local-lvm

### ISSUE THREAD

**Issue by derekgdicamillo** [whiskerz007/proxmox_hassos_install#7]
********************************
 *       Creating new VM        *
 ********************************

storage 'local-lvm' does not exists

**Comment by cooljimy84** [comment]
I've just pushed a patch to the script to check for local-zfs or local- something, as not everyone will have a local storage called "local-lvm"

To run off my patch paste the folllowing

**Comment by cooljimy84** [comment]
TMP=`mktemp -d`;pushd $TMP > /dev/null;wget -qO - **https://raw.githubusercontent.com/whiskerz007/proxmox_hassos_install/371f0a461baccf2a19c3d77e81dfaba9562d8e24/install.sh | bash;popd > /dev/null;rm -rf $TMP;unset TMP

**Comment by whiskerz007** [comment]
@derekgdicamillo Open up a terminal session on Proxmox and run `pvesm status -content images`. This will show you a list of all storage locations for VMs. Find the name of the desired storage pool and replace `local-lvm` (in the oneliner refered to in the README) with the that name.

**Comment by derekgdicamillo** [comment]
Hey Thank you so much! I appreciate this! I am new to proxmox so it's been a learning curve!

**Comment by mrosseel** [comment]
Also struggled with local-zfs, was able to install it with the patched script but then could not resize the disk, getting a 'dataset not found error'.  Will be able to test again next week if further fixes are committed. Thx!

**Comment by cooljimy84** [comment]
I think has something to do with the provisioning of the disk.

**Comment by whiskerz007** [comment]
@derekgdicamillo I have made changes to the repo which should solve your problem. If there is nothing further, I will close this issue after 48 hours.

**Comment by mrosseel** [comment]
I will test next week and let you know, thx

**Comment by whiskerz007** [comment]
@mrosseel No additional concerns have been raised. If there is nothing further, I will close this issue after 48 hours.

**Comment by mrosseel** [comment]
@whiskerz007 haven't had access to the proxmox instance these last weeks, once I do and if there's an error I'll let you know.
