### ISSUE TITLE
Home assistant sruck

### ISSUE THREAD

**Issue by szurr** [whiskerz007/proxmox_hassos_install#77]
Hi 
I have this behavior for some time. If I want restart from console I get:. TASK ERROR: can't lock file '/var/lock/qemu-server/lock-201.conf' - got timeout
In console I have multiple task stop pending timeout.
I have to stop server and manually turn it on and then I have
![Screenshot_20200625-075649](https://user-images.githubusercontent.com/34182435/85664098-24745f00-b6ba-11ea-8e21-40c9da4faa58.jpg)

I gave it 8gb of RAM and 32gb disc and it has lot of free space.

It was installed quite long time ago should I install from newest script or this is not related?
Thanks in advance cheers

**Comment by VarenDerpsAround** [comment]
Read the last line in the console log. The kind of sounds like to me like you're either over provisioning your RAM and it is overcashing and causing deadlocking issues. Or you have a legitimate RAM issue that needs to be taken care of like a burnt RAM stick or something of that sort. I would definitely try to test your RAM to see if the RAM has some faults in it or something like that. But I would also check to make sure you're not using up all of your RAM and more. if you have 8 gig on your system I would stick to 7.5 available between all of your systems running. Do you have a system running 4 gb, in a system running 2 gb, probably shouldn't run a third system on another 4 GB. for having a gigabytes of RAM I see an awful lot of containers. I'm just questioning provisioning the ram correctly.

**Comment by szurr** [comment]
Hi thanks for response
8 gb is for this vm only I started with 2..   inside vm in glances it never go higher than 2gb used. I was told that quemu agent doesn't show real value in proxmox. I can give it 32gb but is there any point or rather problem is somewhere else

**Comment by VarenDerpsAround** [comment]
Show me your hardware tab, please. Thanks.

I still don't know for sure what the issue is, but ram availability shouldn't be it. Show me your hardware tab, and the options tab. I'll compare it to my functioning install.

**Comment by szurr** [comment]
Machine is quite new some 8 months. Xeon e 2246 32 gb of RAM dual nvme in zfs ram. So I don't think that can be hardware.here are screenshots
![Screenshot_20200702-213210](https://user-images.githubusercontent.com/34182435/86402506-3783c200-bcac-11ea-951c-9ce73a80bff4.jpg)
![Screenshot_20200702-213235](https://user-images.githubusercontent.com/34182435/86402517-3e123980-bcac-11ea-9d12-1d5321e4a686.jpg)

I have also another home assistant ( dev) it has minimal add-ons and I don't have same problems. There is a difference in time of installation script. The dev is around 3 months old and main one is same as server so around 8 months.

**Comment by VarenDerpsAround** [comment]
My first thing I would try would be to turn off ram ballooning. In the ram setting set it to at least 3 gig minimum. And turn off ballooning perhaps. One or the other or both. I see your minimum is quite low so perhaps turn up the minimum to something like 3 gig. But if that doesn't work turning off ballooning entirely would just give it the 8 gig and be done with it. I don't know maybe start there. At this point you're not going to break anything else. At least not with doing that.

**Comment by szurr** [comment]
Thanks I will try removing ballooning. In fact since I write first post all is ok so maybe lastest trimming of home assistant has something to do with it

**Comment by VarenDerpsAround** [comment]
> Thanks I will try removing ballooning. In fact since I write first post all is ok so maybe lastest trimming of home assistant has something to do with it
> To be honest I thought that I have minimal 1 gb of ram

do me a favor bud? and scrub/delete your photos? close the ticket perhaps? but definitely scrub the photos, I don't see anything that sticks out but there is alot there. 

cheers.
