### ISSUE TITLE
Script Stalls

### ISSUE THREAD

**Issue by Photo64** [whiskerz007/proxmox_hassos_install#8]
After clicking "Start" the script runs for a while then it stalls with no error message. It stops at:
[ ok ] Started Docker Application Container Engine. 

I've tried to restarting a few times but it continually stalls at this point.

**Comment by cooljimy84** [comment]
Do you mean the Virtual machine stalls at "[ ok ] Started Docker Application Container Engine."
as the script is run on the shell part of the host, and doesn't start the machine after it's created it.

**Comment by Photo64** [comment]
Yes. I reran the install a couple of times and did notice two failed statements as the script was running through the console. I had to rerun it a few times to capture it since there is no way to scroll back. The 1st one was: "Failed to start Network Manager wait online" and the 2nd was: " Failed to Start Docker Application Container". Both of these appeared I was say around the middle of the script and it goes by quickly. It then proceeds to the "[ ok ] Started Docker Application Container Engine" and just stalls. I tried waiting over 30 minutes but it doesn't appear to be moving forward at all.  I should note that I have Proxmox installed on an older Core 2 Duo Laptop. Could any of these be impacting why it is not proceeding?

**Comment by cooljimy84** [comment]
So thats not the script, thats just the virtual machine booting (I gather from you saying yes)
what happens if you press enter a few times when your in the console of that virtual machine.

Have you installed Proxmox on to the laptop ?
the processor is quite old, but should support Proxmox fine.

**Comment by Photo64** [comment]
Proxmox is installed on the laptop and appears to be running fine. Pressing enter does nothing in the console. I actually tried the other approach from Dr Zzzs video using MarkM's script and it stops at the same spot in the console. It also looks like it is running and I do see an ip address in my router however when I try to connect to it the web page refuses connection.

**Comment by cooljimy84** [comment]
Are you using the wireless on the laptop as the bridge device ? or are you cabled in ?

**Comment by Photo64** [comment]
I am using an Ethernet cable on the laptop

**Comment by cooljimy84** [comment]
Sorry that was my final idea of what it could be, I've run the script on 3 different boxes (not quite as old as core2duo) and it worked fine.

**Comment by Photo64** [comment]
I was hoping for a minor miracle, wanted to play with a dev version of hassio under proxmox. Looks like I'll need a better machine.
