### ISSUE TITLE
Nothing happens when running command

### ISSUE THREAD

**Issue by derrey** [whiskerz007/proxmox_hassos_install#81]
Hi, I was trying to install Home Assistant on a new install of Proxmox 6.2-4.
When running the command: 
bash -c "$(wget -qLO - https://github.com/whiskerz007/proxmox_hassos_install/raw/master/install.sh)"

It just returns the # prompt without running anything.

**Comment by RoldyBuffalo** [comment]
> 
> 
> Hi, I was trying to install Home Assistant on a new install of Proxmox 6.2-4.
> When running the command:
> bash -c "$(wget -qLO - https://github.com/whiskerz007/proxmox_hassos_install/raw/master/install.sh)"
> 
> It just returns the # prompt without running anything.


Check your DNS settings on proxmox, also you can try to remove the -c as that is the directive for silent install I believe.

**Comment by derrey** [comment]
After removing the -c I get the file can't be found. 
bash: : No such file or directory

Then I tried just to wget the file directly and get this error.

--2040-10-19 04:47:17--  https://github.com/whiskerz007/proxmox_hassos_install/raw/master/install.sh
Resolving github.com (github.com)... 140.82.112.4
Connecting to github.com (github.com)|140.82.112.4|:443... connected.
ERROR: The certificate of ‘github.com’ is not trusted.
ERROR: The certificate of ‘github.com’ has expired.

**Comment by RoldyBuffalo** [comment]
I'm not sure, hopefully @whiskerz007  has some better idea. Odd it would say github.com is not trusted, it's clearly ssl encrypted on the site, and on the link. No special dns running on your system that would interfere?

**Comment by derrey** [comment]
Thanks for your help... I was able to solve the issue. It was a very simple fix but hard to find :) 
It looks like the new computer had the year set to 2040 and that made everything look expired. 
After a few hours of trying to fix the expired items.. I stumbled across it.

**Comment by RoldyBuffalo** [comment]
Oh jeeze, I've done that before. It's just been so long since I've had a pc / device without automatic NTP updates that I forgot ssl certs don't work if your date is off DUH! Good stuff bud! Glad you got it sorted!

**Comment by RoldyBuffalo** [comment]
> --20(40)-10-19 04:47:17-- https://github.com/whiskerz007/proxmox_hassos_install/raw/master/install.sh

bahaha, it was even right here!
