### ISSUE TITLE
Home Assistant won't start

### ISSUE THREAD

**Issue by CasparTheBridge** [whiskerz007/proxmox_hassos_install#84]
The VM is creating good and all steps are successful but when I try to start the VM the console shows the following message/error and won't correctly start:
BLK0: Alias(s):
PciRoot (0x0)/Pci (0x7,0x0) / Sata (0x0,0xFFFF,0x0)
BLK2:
PciRoot (0x0)/Pci (0x7,0x0) / Sata (0x0,0xFFFF,0x0)/HD(2,GPT,26700FC6-B0BC-4CCF-9837-EA1A4CBA3E65,0x10800,0xC000)
BLK3:
PciRoot...
BLK4:
PciRoot...
BLK5:
PciRoot...
BLK6:
PciRoot...
BLK7:
PciRoot...
BLK8:
PciRoot...
Press ESC in 1 second s to skip startup.nsh or any other key to continue.
Shell> 

Any suggestions where to look at?

**Comment by CasparTheBridge** [comment]
![Uploading Schermafbeelding 2020-11-15 om 13.34.18.png…]()

**Comment by CasparTheBridge** [comment]
In the xterm console there is some information more from the start:
<img width="1121" alt="Schermafbeelding 2020-11-15 om 20 18 08" src="https://user-images.githubusercontent.com/50670032/99194460-cf77d900-277f-11eb-8110-e9f119ad58d0.png">

**Comment by CasparTheBridge** [comment]
Oops.. The boot order was not correct..
Selecting the Sata0 instead of the net0 fixed it :)

**Comment by darazi** [comment]
Having a similar error:
Though it seems to have something to do with the PCI. 
Any ideas? 
<img width="390" alt="error" src="https://user-images.githubusercontent.com/30054792/213903817-1d43edb8-d4b1-4596-83a2-3076aa5e7e61.PNG">


Resolved:
secure boot needed to be removed from the VM
