### ISSUE TITLE
This script has never worked for me, tried it again today and still no good - would love to understand why...

### ISSUE THREAD

**Issue by mf-social** [whiskerz007/proxmox_hassos_install#86]
Hi,

I have tried this script several times in the past and it has never worked, I've always ended up in the exact same position.  But it clearly works for lots of people and I'd like to understand why it never works for me.  So here's today's adventure, please feel free to tell me where I am going wrong...

Today, thanks to hard-drive failure earlier in the week, I've built a brand spanking new Proxmox server.  Fresh install, nothing changed except disabling the 'enterprise' repos as I do not have a subscription.

The very first thing I have then done is run this script.  To do this, following the instructions on the readme, I opened the console window and pasted the command into it:

```
bash -c "$(wget -qLO - https://github.com/whiskerz007/proxmox_hassos_install/raw/master/install.sh)"
```

The script ran and said it was successful.

Then, as per the readme, I set the RAM to 2048, the CPU to 2, and the HDD to 100G

Then, as per the readme, I pressed start.

Now, all of the above don't seem to be complicated instructions, and I've read the readme like a thousand times.  But everyone else seems to get a homeassistant install at this point, This is what I get...

If I try and open a console window with xterm it sits on "starting serial terminal on interface serial0" - and just stays like that forever (well, at least an hour so far).

If I open a console window with NoVNX I have a command prompt that says "SHELL> " - no homeassistant login as suggested by the readme.  Readme actually suggest pressing enter a couple of times to get that prompt.  I've pressed it 20, all it does is go to the next line and repeat "SHELL>".

Nothing works from the SHELL> command prompt.  No cd, no ls, no nothing.  Just "Command not found" type errors.

So, I figure, who needs the cli anyway, lets see if homeassistant is running.   Of course if I try to use the nmcli command from the readme at the SHELL> prompt, that doesn't work.  The other option in the readme says to look under IP's in the summary page of the proxmox interface.  Here I see " IPs - Guest Agent not running"

According to my routers DHCP table, this VM has not connected.

🤷‍♂️

**Comment by mf-social** [comment]
Just as an interesting point, after giving up with this script I tried to use the qcow2 image (following this guide: https://community.home-assistant.io/t/supervised-install-on-proxmox/194460 ) for hassos in my proxmox and that does exactly the same.  Boots to a SHELL> prompt and doesn't do anything further, so it may well not be your script that I'm having issues with, but the hassos image itself, but I would have expected your script to setup the VM correctly and remove any potential for human error in importing the qcow2 image and setting up the VM manually (although again, the instructions aren't particularly complicated so I don't have a clue why it's not working).

Creating a new VM with debian and performing a "Supervised install" (from here: https://github.com/home-assistant/supervised-installer) works fine 🤷‍♂️

**Comment by ullebe1** [comment]
I had to go to "Options" and change the "Boot Order" so it boots from "sata0" rather than "net0". What is that set to for you?

**Comment by Vulp35** [comment]
> 
> 
> Just as an interesting point, after giving up with this script I tried to use the qcow2 image (following this guide: https://community.home-assistant.io/t/supervised-install-on-proxmox/194460 ) for hassos in my proxmox and that does exactly the same. Boots to a SHELL> prompt and doesn't do anything further, so it may well not be your script that I'm having issues with, but the hassos image itself, but I would have expected your script to setup the VM correctly and remove any potential for human error in importing the qcow2 image and setting up the VM manually (although again, the instructions aren't particularly complicated so I don't have a clue why it's not working).
> 
> Creating a new VM with debian and performing a "Supervised install" (from here: https://github.com/home-assistant/supervised-installer) works fine 🤷‍♂️

when given the `SHELL>` I just typed exit then navigated to Boot Devices and selected the hard disc. This allowed me to boot all the way up so I could properly shut it down then do as @ullebe1 says above

> 
> 
> I had to go to "Options" and change the "Boot Order" so it boots from "sata0" rather than "net0". What is that set to for you?

**Comment by mf-social** [comment]
@ullebe1 & @Vulp35 thanks for the responses. I won't be able to look at this again until next weekend, but I will see if the combination of your suggestions works.

I'm curious why this has happened to the 3 of us though. Or does it happen to everyone? If so, why are these steps not documented?

**Comment by bvduijv** [comment]
Same here. Thanks for the solution!

**Comment by HFeenstra** [comment]
> I had to go to "Options" and change the "Boot Order" so it boots from "sata0" rather than "net0". What is that set to for you?

Hi, I can confirm this solution works, for me. So in Shell I typed exit
The VM comes in start options menu, selected the boot management options and changed the order of booting, saved it and VM came up no problem.

**Comment by mf-social** [comment]
I still haven't got back to this (hopefully Sunday!) but it looks promising that several people seem to be fixing this with the advice above 🙂

It also seems that this is a fairly common issue. Anyone know why? 

Once I've sorted it out my end I'll submit a PR to add the additional instructions to the README, but would still love to know why this is happening to some of us and not others 🤷‍♂️

**Comment by HFeenstra** [comment]
To add to my earlier reply, this was the first time I had issues with this VM. 
So again the steps I describe earlier are the ones who also work for me after several reboots. 
Perhaps Whiskerz can say anything about this?

**Comment by HFeenstra** [comment]
@mf-social I can confirm the new install.sh, tweaked by @ Najihel works. The boot order has neem fixed so the VM comes up after a reboot of Prixmox.

**Comment by mf-social** [comment]
Magic, I'll close this then and hopefully get round to trying it out again at some point between now and the apocalypse 🙈

Thanks everyone for your inputs. 👍
