### ISSUE TITLE
Stuck at "Storage Pools" screen when running command

### ISSUE THREAD

**Issue by CullenJWebb** [whiskerz007/proxmox_hassos_install#88]
I run the command and I see this screen:
![storage pools](https://user-images.githubusercontent.com/2952787/101271387-36215e80-3750-11eb-8b5c-c5c3e74cc9d4.png)

I try to select any of the 3 options but none of them work, it just goes back to the top option.

I'm probably missing something obvious. Any advice would be appreciated.

**Comment by AlecVercruysse** [comment]
Having the same issue here

**Comment by CraftyKoala** [comment]
Did you press space to select an option and enter to continue ?

**Comment by CullenJWebb** [comment]
> 
> 
> Did you press space to select an option and enter to continue ?

...no.

It's working now. Thanks!

**Comment by CullenJWebb** [comment]
(I was trying keys other than space to select the storage pool)
