### ISSUE TITLE
Script fails - 400 Parameter verification failed. ; boot: value does not match the regex pattern

### ISSUE THREAD

**Issue by jplivingston08** [whiskerz007/proxmox_hassos_install#90]
I have used this script in the past and it worked perfectly.  Wanted to spin up a new copy today and unfortunately the below error occurs while the script is running.  

root@px2:~# bash -c "$(wget -qLO - https://github.com/whiskerz007/proxmox_hassos_install/raw/master/install.sh)"

[INFO] Using 'local-lvm' for storage location.
[INFO] Container ID is 102.
Getting URL for latest Home Assistant disk image...
Downloading disk image...
Extracting disk image...
Creating VM...
400 Parameter verification failed.
boot: value does not match the regex pattern
qm set <vmid> [OPTIONS]
[ERROR] 255@140 Unknown failure occured.
  Logical volume "vm-102-disk-1" successfully removed
  Logical volume "vm-102-disk-0" successfully removed

**Comment by jplivingston08** [comment]
I ran this and then I was able to run the script successfully:
sudo apt update && sudo apt dist-upgrade -y && sudo apt install qemu-guest-agent -y && sudo apt autoremove --purge -y

**Comment by SimonEverett** [comment]
Haveing the same issuie,Virtual Environment 5.3-8 the apt install didnt help.
